// words.js
const words = [
  {char:"爸爸", zhuyin:"ㄅㄚˋ ㄅㄚ˙"},
  {char:"媽媽", zhuyin:"ㄇㄚ ㄇㄚ˙"},
  {char:"哥哥", zhuyin:"ㄍㄜ ㄍㄜ˙"},
  {char:"姐姐", zhuyin:"ㄐㄧㄝˇ ㄐㄧㄝ˙"},
  {char:"弟弟", zhuyin:"ㄉㄧˋ ㄉㄧ˙"},
  {char:"妹妹", zhuyin:"ㄇㄟˋ ㄇㄟ˙"},
  {char:"貓咪", zhuyin:"ㄇㄠ ㄇㄧ"},
  {char:"小朋友", zhuyin:"ㄒㄧㄠˇ ㄆㄥˊ ㄧㄡˇ"},
  {char:"火車", zhuyin:"ㄏㄨㄛˇ ㄔㄜ"},
  {char:"太陽", zhuyin:"ㄊㄞˋ ㄧㄤˋ"},
  {char:"月亮", zhuyin:"ㄩㄝˋ ㄌㄧㄤˋ"},
  {char:"白兔子", zhuyin:"ㄅㄞˊ ㄊㄨˋ ㄗ˙"},
  {char:"紅蘋果", zhuyin:"ㄏㄨㄥˊ ㄆㄧㄥˊ ㄍㄨㄛˇ"},
  {char:"藍天空", zhuyin:"ㄌㄢˊ ㄊㄧㄢ ㄎㄨㄥ"},
  {char:"水杯", zhuyin:"ㄕㄨㄟˇ ㄅㄟ"},
  {char:"木頭", zhuyin:"ㄇㄨˋ ㄊㄡˊ"},
  {char:"雨傘", zhuyin:"ㄩˇ ㄙㄢˇ"},
  {char:"電腦", zhuyin:"ㄉㄧㄢˋ ㄋㄠˇ"},
  {char:"手機", zhuyin:"ㄕㄡˇ ㄐㄧ"},
  {char:"書包", zhuyin:"ㄕㄨ ㄅㄠ"},
  {char:"鉛筆", zhuyin:"ㄑㄧㄢ ㄅㄧˇ"},
  {char:"橡皮擦", zhuyin:"ㄒㄧㄤˋ ㄆㄧˊ ㄘㄚ"},
  {char:"桌子", zhuyin:"ㄓㄨㄛ ㄗ˙"},
  {char:"椅子", zhuyin:"ㄧˇ ㄗ˙"},
  {char:"黑板", zhuyin:"ㄏㄟ ㄅㄢˇ"},
  {char:"教室", zhuyin:"ㄐㄧㄠˋ ㄕˋ"},
  {char:"老師", zhuyin:"ㄌㄠˇ ㄕ"},
  {char:"學生", zhuyin:"ㄒㄩㄝˊ ㄕㄥ"},
  {char:"玩具", zhuyin:"ㄨㄢˊ ㄐㄩˋ"},
  {char:"球類", zhuyin:"ㄑㄧㄡˊ ㄌㄟˋ"},
  {char:"水果", zhuyin:"ㄕㄨㄟˇ ㄍㄨㄛˇ"},
  {char:"香蕉", zhuyin:"ㄒㄧㄤ ㄐㄧㄠ"},
  {char:"西瓜", zhuyin:"ㄒㄧ ㄍㄨㄚ"},
  {char:"蘋果", zhuyin:"ㄆㄧㄥˊ ㄍㄨㄛˇ"},
  {char:"橘子", zhuyin:"ㄐㄩˊ ㄗ˙"},
  {char:"天空", zhuyin:"ㄊㄧㄢ ㄎㄨㄥ"},
  {char:"白雲", zhuyin:"ㄅㄞˊ ㄩㄣˊ"},
  {char:"小鳥", zhuyin:"ㄒㄧㄠˇ ㄋㄧㄠˇ"},
  {char:"蝴蝶", zhuyin:"ㄏㄨˊ ㄉㄧㄝˊ"},
  {char:"花朵", zhuyin:"ㄏㄨㄚ ㄉㄨㄛˇ"},
  {char:"草地", zhuyin:"ㄘㄠˇ ㄉㄧˋ"},
  {char:"河流", zhuyin:"ㄏㄜˊ ㄌㄧㄡˊ"},
  {char:"大海", zhuyin:"ㄉㄚˋ ㄏㄞˇ"},
  {char:"山峰", zhuyin:"ㄕㄢ ㄈㄥ"},
  {char:"森林", zhuyin:"ㄙㄣ ㄌㄧㄣˊ"},
  {char:"汽車", zhuyin:"ㄑㄧˋ ㄔㄜ"},
  {char:"飛機", zhuyin:"ㄈㄟ ㄐㄧ"},
  {char:"船隻", zhuyin:"ㄔㄨㄢˊ ㄓ"},
  {char:"火山", zhuyin:"ㄏㄨㄛˇ ㄕㄢ"},
  {char:"冰山", zhuyin:"ㄅㄧㄥ ㄕㄢ"},
  {char:"河邊", zhuyin:"ㄏㄜˊ ㄅㄧㄢ"},
  {char:"草原", zhuyin:"ㄘㄠˇ ㄩㄢˊ"}
];

